// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.13.0
// source: lucy_proto/testing/hogwarts.proto

package prototesting

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// House is an enum of Hogwarts Houses.
type House int32

const (
	House_Gryffindor House = 0
	House_Ravenclaw  House = 1
	House_Hufflepuff House = 2
	House_Slytherin  House = 3
)

// Enum value maps for House.
var (
	House_name = map[int32]string{
		0: "Gryffindor",
		1: "Ravenclaw",
		2: "Hufflepuff",
		3: "Slytherin",
	}
	House_value = map[string]int32{
		"Gryffindor": 0,
		"Ravenclaw":  1,
		"Hufflepuff": 2,
		"Slytherin":  3,
	}
)

func (x House) Enum() *House {
	p := new(House)
	*p = x
	return p
}

func (x House) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (House) Descriptor() protoreflect.EnumDescriptor {
	return file_lucy_proto_testing_hogwarts_proto_enumTypes[0].Descriptor()
}

func (House) Type() protoreflect.EnumType {
	return &file_lucy_proto_testing_hogwarts_proto_enumTypes[0]
}

func (x House) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use House.Descriptor instead.
func (House) EnumDescriptor() ([]byte, []int) {
	return file_lucy_proto_testing_hogwarts_proto_rawDescGZIP(), []int{0}
}

// Student holds a student's name.
type Student struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Student) Reset() {
	*x = Student{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lucy_proto_testing_hogwarts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_lucy_proto_testing_hogwarts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_lucy_proto_testing_hogwarts_proto_rawDescGZIP(), []int{0}
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Sorted holds the house the student was sorted into.
type Sorted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	House House `protobuf:"varint,1,opt,name=house,proto3,enum=lucy.testing.House" json:"house,omitempty"`
}

func (x *Sorted) Reset() {
	*x = Sorted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lucy_proto_testing_hogwarts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sorted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sorted) ProtoMessage() {}

func (x *Sorted) ProtoReflect() protoreflect.Message {
	mi := &file_lucy_proto_testing_hogwarts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sorted.ProtoReflect.Descriptor instead.
func (*Sorted) Descriptor() ([]byte, []int) {
	return file_lucy_proto_testing_hogwarts_proto_rawDescGZIP(), []int{1}
}

func (x *Sorted) GetHouse() House {
	if x != nil {
		return x.House
	}
	return House_Gryffindor
}

var File_lucy_proto_testing_hogwarts_proto protoreflect.FileDescriptor

var file_lucy_proto_testing_hogwarts_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6c, 0x75, 0x63, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x2f, 0x68, 0x6f, 0x67, 0x77, 0x61, 0x72, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6c, 0x75, 0x63, 0x79, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x22, 0x1d, 0x0a, 0x07, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x33, 0x0a, 0x06, 0x53, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x05, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6c, 0x75, 0x63, 0x79,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x05,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x2a, 0x45, 0x0a, 0x05, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x0a, 0x47, 0x72, 0x79, 0x66, 0x66, 0x69, 0x6e, 0x64, 0x6f, 0x72, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x52, 0x61, 0x76, 0x65, 0x6e, 0x63, 0x6c, 0x61, 0x77, 0x10, 0x01, 0x12, 0x0e, 0x0a,
	0x0a, 0x48, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x70, 0x75, 0x66, 0x66, 0x10, 0x02, 0x12, 0x0d, 0x0a,
	0x09, 0x53, 0x6c, 0x79, 0x74, 0x68, 0x65, 0x72, 0x69, 0x6e, 0x10, 0x03, 0x42, 0x32, 0x5a, 0x30,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x65, 0x61, 0x6b, 0x65,
	0x31, 0x30, 0x30, 0x2f, 0x6c, 0x75, 0x63, 0x79, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lucy_proto_testing_hogwarts_proto_rawDescOnce sync.Once
	file_lucy_proto_testing_hogwarts_proto_rawDescData = file_lucy_proto_testing_hogwarts_proto_rawDesc
)

func file_lucy_proto_testing_hogwarts_proto_rawDescGZIP() []byte {
	file_lucy_proto_testing_hogwarts_proto_rawDescOnce.Do(func() {
		file_lucy_proto_testing_hogwarts_proto_rawDescData = protoimpl.X.CompressGZIP(file_lucy_proto_testing_hogwarts_proto_rawDescData)
	})
	return file_lucy_proto_testing_hogwarts_proto_rawDescData
}

var file_lucy_proto_testing_hogwarts_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lucy_proto_testing_hogwarts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lucy_proto_testing_hogwarts_proto_goTypes = []interface{}{
	(House)(0),      // 0: lucy.testing.House
	(*Student)(nil), // 1: lucy.testing.Student
	(*Sorted)(nil),  // 2: lucy.testing.Sorted
}
var file_lucy_proto_testing_hogwarts_proto_depIdxs = []int32{
	0, // 0: lucy.testing.Sorted.house:type_name -> lucy.testing.House
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lucy_proto_testing_hogwarts_proto_init() }
func file_lucy_proto_testing_hogwarts_proto_init() {
	if File_lucy_proto_testing_hogwarts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lucy_proto_testing_hogwarts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Student); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lucy_proto_testing_hogwarts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sorted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lucy_proto_testing_hogwarts_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lucy_proto_testing_hogwarts_proto_goTypes,
		DependencyIndexes: file_lucy_proto_testing_hogwarts_proto_depIdxs,
		EnumInfos:         file_lucy_proto_testing_hogwarts_proto_enumTypes,
		MessageInfos:      file_lucy_proto_testing_hogwarts_proto_msgTypes,
	}.Build()
	File_lucy_proto_testing_hogwarts_proto = out.File
	file_lucy_proto_testing_hogwarts_proto_rawDesc = nil
	file_lucy_proto_testing_hogwarts_proto_goTypes = nil
	file_lucy_proto_testing_hogwarts_proto_depIdxs = nil
}
